### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by OmgImAlexis** [IonicaBizau/github-stats#12]
```
➜  yarn global add github-stats
yarn global v0.27.5
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
warning github-stats > ghcal > cheerio > CSSselect@0.4.1: the module is now available as 'css-select'
warning github-stats > ghcal > cheerio > CSSselect > CSSwhat@0.4.7: the module is now available as 'css-what'
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⢀ websocket
[2/2] ⢀ github-colors: ERR!     /Users/xo/.npm/_logs/2017-07-11T08_03_13_891Z-debug.log
[-/2] ⢀ waiting...
[-/2] ⢀ waiting...
error /Users/xo/.config/yarn/global/node_modules/github-colors: Command failed.
Exit code: 1
Command: sh
Arguments: -c npm run build
Directory: /Users/xo/.config/yarn/global/node_modules/github-colors
Output:
> github-colors@2.2.12 build /Users/xo/.config/yarn/global/node_modules/github-colors
> node ./build/main

module.js:487
    throw err;
    ^

Error: Cannot find module '/Users/xo/.config/yarn/global/node_modules/github-colors/build/main'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github-colors@2.2.12 build: `node ./build/main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the github-colors@2.2.12 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xo/.npm/_logs/2017-07-11T08_03_13_891Z-debug.log
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by mef** [comment]
I have the same problem.

Worked around it by first installing an older version of github-colors (which fails to install as of v2.2.11):

````bash
npm i github-colors@2.2.10
npm i github-stats
````

**Comment by IonicaBizau** [comment]
Thanks for these! ✨ 

I released a patch version in `github-stats`. I didn't work with `yarn` a lot. Make sure it's going to download the latest version.

Let me know if it's working! 😄

**Comment by OmgImAlexis** [comment]
Yep it's working perfectly now. 👍

**Comment by IonicaBizau** [comment]
🎉🎉🎉
