### ISSUE TITLE
Crash when `process.stdout.rows` ≤ 18

### ISSUE THREAD

**Issue by rbtr** [IonicaBizau/github-stats#17]
Like the title says, if the console rows are 18 or less, `cli-pie` gets passed a negative number for a radius. This eventually throws in exception in `cli-graph` because of a chain of failures.

```
...cli-graph/lib/index.js:63
    self.graph[settings.center.y][settings.center.x] = settings.marks.center;
                                                     ^

TypeError: Cannot set property '0' of undefined
    at new CliGraph (...cli-graph/lib/index.js:63:54)
    at new CliCircle (...cli-circle/lib/index.js:35:18)
    at CliPie.toString (...cli-pie/lib/index.js:170:18)
    at done (...github-stats/lib/index.js:192:20)
```

I think this is due to the auto-sizing calculation [here](https://github.com/IonicaBizau/github-stats/blob/master/lib/index.js#L52) ending up negative. 

The best fix IMO is to not allow there to be less than 19 rows. At any smaller scale than 21 the pie does not even show up. Making the user scroll a line or two seems like an ok tradeoff.

**Comment by rbtr** [comment]
i might have misdiagnosed this slightly. the ul.merge [here](https://github.com/IonicaBizau/github-stats/blob/master/lib/index.js#L57) just needs the argument order reversed. currently the first (negative) values are being returned by the merge.
